"""Initial schema: tracking database, ported from SQLite.

Hand-transcribed from strategic_reports/daily/core/db.py's old _SCHEMA
string (git history has the SQLite version), not autogenerated — this
codebase has no SQLAlchemy metadata/models to diff against, since every
DB-touching module writes plain SQL directly against psycopg.

Differences from the SQLite original, all deliberate:
  - INTEGER PRIMARY KEY AUTOINCREMENT -> GENERATED ALWAYS AS IDENTITY
    (Postgres-native, preferred over SERIAL).
  - REFERENCES ... is now an enforced foreign key (SQLite declared these
    but never enforced them — no PRAGMA foreign_keys=ON anywhere). Safe to
    enable from day one here because Postgres starts with an empty
    database (no data migrated in from the old SQLite file), so there's no
    latent-orphan risk from existing data to audit first.
  - created_at stays TEXT (ISO 8601 UTC strings via datetime.isoformat()),
    not TIMESTAMPTZ — upgrading that is deliberately out of scope for this
    migration (string ISO-8601 sort order already works correctly on both
    engines), flagged as separate future work.

Revision ID: 0001
Revises:
Create Date: 2026-08-13
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "runs",
        sa.Column("run_id", sa.Text, primary_key=True),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("article_count", sa.Integer, nullable=False),
    )

    op.create_table(
        "urgency_scores",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("topic", sa.Text, nullable=False),
        sa.Column("score", sa.Float, nullable=False),
    )
    op.create_index("idx_urgency_scores_topic", "urgency_scores", ["topic", "created_at"])

    op.create_table(
        "bullets",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("topic", sa.Text, nullable=False),
        sa.Column("bullet_index", sa.Integer, nullable=False),
        sa.Column("bullet_text", sa.Text, nullable=False),
    )
    op.create_index("idx_bullets_topic", "bullets", ["topic", "created_at"])

    # The three tables below let a given run's tag_graph.json be
    # reconstructed from the database (see tag_tracking.rebuild_graph_data)
    # and let a tag's rate (count / that run's article_count) be tracked
    # over time for emerging-tag z-score alerts (see
    # tag_tracking.check_emerging_tags).
    op.create_table(
        "tag_counts",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
        sa.Column("count", sa.Integer, nullable=False),
    )
    op.create_index("idx_tag_counts_tag", "tag_counts", ["tag", "created_at"])
    op.create_index("idx_tag_counts_run", "tag_counts", ["run_id"])

    op.create_table(
        "tag_topics",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
        sa.Column("topic", sa.Text, nullable=False),
    )
    op.create_index("idx_tag_topics_run_tag", "tag_topics", ["run_id", "tag"])

    op.create_table(
        "tag_edges",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag_a", sa.Text, nullable=False),
        sa.Column("tag_b", sa.Text, nullable=False),
        sa.Column("weight", sa.Integer, nullable=False),
    )
    op.create_index("idx_tag_edges_run", "tag_edges", ["run_id"])

    # Audit trail of emerging-tag alerts that actually fired (not every
    # tag's rate/z-score every run — those are always recomputable from
    # tag_counts + runs.article_count via tag_tracking.load_tag_rate_history).
    op.create_table(
        "emerging_tag_alerts",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
        sa.Column("count", sa.Integer, nullable=False),
        sa.Column("rate", sa.Float, nullable=False),
        sa.Column("mean", sa.Float, nullable=False),
        sa.Column("std", sa.Float, nullable=False),
        sa.Column("z_score", sa.Float, nullable=False),
    )
    op.create_index("idx_emerging_tag_alerts_tag", "emerging_tag_alerts", ["tag", "created_at"])
    op.create_index("idx_emerging_tag_alerts_run", "emerging_tag_alerts", ["run_id"])

    # Audit trail of the bridge tags actually surfaced to the cross-topic
    # synthesis prompt each run (see tag_graph.find_bridge_tags and
    # pipeline.synthesize_cross_topic). Self-contained — stores its own
    # topics rather than joining against tag_topics.
    op.create_table(
        "bridge_tags",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
        sa.Column("count", sa.Integer, nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
    )
    op.create_index("idx_bridge_tags_run", "bridge_tags", ["run_id"])
    op.create_index("idx_bridge_tags_tag", "bridge_tags", ["tag", "created_at"])

    op.create_table(
        "bridge_tag_topics",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
        sa.Column("topic", sa.Text, nullable=False),
    )
    op.create_index("idx_bridge_tag_topics_run_tag", "bridge_tag_topics", ["run_id", "tag"])

    # Persists each run's article summaries (title, link, publish_date,
    # summary bullets, tags) — the source material every derived signal
    # (tag_counts, bullets, urgency_scores) is computed from. See
    # article_archive.py.
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("topic", sa.Text, nullable=False),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("link", sa.Text, nullable=False),
        sa.Column("publish_date", sa.Text, nullable=False),
    )
    op.create_index("idx_articles_run", "articles", ["run_id"])
    op.create_index("idx_articles_topic", "articles", ["topic", "created_at"])

    op.create_table(
        "article_summary_bullets",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("article_id", sa.BigInteger, sa.ForeignKey("articles.id"), nullable=False),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("bullet_index", sa.Integer, nullable=False),
        sa.Column("bullet_text", sa.Text, nullable=False),
    )
    op.create_index(
        "idx_article_summary_bullets_article", "article_summary_bullets", ["article_id"]
    )

    op.create_table(
        "article_tags",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("article_id", sa.BigInteger, sa.ForeignKey("articles.id"), nullable=False),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
    )
    op.create_index("idx_article_tags_article", "article_tags", ["article_id"])
    op.create_index("idx_article_tags_tag", "article_tags", ["tag", "created_at"])

    # LLM-written summary of each Louvain tag-community's news coverage
    # this run (see tag_graph.group_articles_by_community and
    # pipeline.summarize_communities). Self-contained: stores each
    # community's own member tags rather than reconstructing them from
    # tag_counts.
    op.create_table(
        "community_summaries",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("community_id", sa.Integer, nullable=False),
        sa.Column("label", sa.Text, nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column("article_count", sa.Integer, nullable=False),
    )
    op.create_index("idx_community_summaries_run", "community_summaries", ["run_id"])

    op.create_table(
        "community_summary_tags",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("community_id", sa.Integer, nullable=False),
        sa.Column("tag", sa.Text, nullable=False),
    )
    op.create_index(
        "idx_community_summary_tags_run_comm",
        "community_summary_tags",
        ["run_id", "community_id"],
    )

    # The cross-topic synthesis overview (see pipeline.synthesize_cross_topic)
    # is rendered into index.html but was otherwise never persisted before
    # overview_archive.py. One row per bullet.
    op.create_table(
        "cross_topic_overviews",
        sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
        sa.Column("run_id", sa.Text, sa.ForeignKey("runs.run_id"), nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("bullet_index", sa.Integer, nullable=False),
        sa.Column("bullet_text", sa.Text, nullable=False),
    )
    op.create_index("idx_cross_topic_overviews_run", "cross_topic_overviews", ["run_id"])


def downgrade() -> None:
    op.drop_table("cross_topic_overviews")
    op.drop_table("community_summary_tags")
    op.drop_table("community_summaries")
    op.drop_table("article_tags")
    op.drop_table("article_summary_bullets")
    op.drop_table("articles")
    op.drop_table("bridge_tag_topics")
    op.drop_table("bridge_tags")
    op.drop_table("emerging_tag_alerts")
    op.drop_table("tag_edges")
    op.drop_table("tag_topics")
    op.drop_table("tag_counts")
    op.drop_table("bullets")
    op.drop_table("urgency_scores")
    op.drop_table("runs")
